---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver:
      box: janihur/ubuntu-1404-desktop

suites:
  - name: default
    run_list:
      - recipe[sublime-text::default]